/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Mapping of English transliterated Hijri months to Bengali
const HIJRI_MONTHS_BENGALI: { [key: string]: string } = {
  'Muharram': 'মহররম',
  'Safar': 'সফর',
  'Rabiʻ I': 'রবিউল আউয়াল',
  'Rabiʻ II': 'রবিউস সানি',
  'Jumada I': 'জমাদিউল আউয়াল',
  'Jumada II': 'জমাদিউস সানি',
  'Rajab': 'রজব',
  'Shaʻban': 'শাবান',
  'Ramadan': 'রমজান',
  'Shawwal': 'শাওয়াল',
  'Dhuʻl-Qiʻdah': 'জিলকদ',
  'Dhuʻl-Hijjah': 'জিলহজ',
  // Alternate spellings/formats generated by Intl
  'Rabi\' al-Awwal': 'রবিউল আউয়াল',
  'Rabi\' al-Thani': 'রবিউস সানি',
  'Jumada al-Awwal': 'জমাদিউল আউয়াল',
  'Jumada al-Thani': 'জমাদিউস সানি',
  'Dhu al-Qi\'dah': 'জিলকদ',
  'Dhu al-Hijjah': 'জিলহজ',
};

/**
 * Converts a Gregorian YYYY-MM-DD string into beautiful Arabic & Transliterated Hijri representations
 */
export function convertGregorianToHijri(dateStr: string): { 
  arabic: string;      // e.g. "٤ ذو الحجة ١٤٤٧"
  latin: string;       // e.g. "4 Dhu al-Hijjah 1447"
  bengali: string;     // e.g. "৪ জিলহজ ১৪৪৭"
} {
  if (!dateStr) return { arabic: '', latin: '', bengali: '' };
  
  const date = new Date(dateStr);
  if (isNaN(date.getTime())) {
    return { arabic: '', latin: '', bengali: '' };
  }

  try {
    let y = date.getFullYear();
    let m = date.getMonth() + 1; // 1-12
    let d = date.getDate();

    if (m <= 2) {
      y -= 1;
      m += 12;
    }

    const A = Math.floor(y / 100);
    const B = Math.floor(A / 4);
    const C = 2 - A + B;
    const E = Math.floor(365.25 * (y + 4716));
    const F = Math.floor(30.6001 * (m + 1));
    const jd = C + d + E + F - 1524.5;

    // Saudi Um Al-Qura alignment factor
    const ksaAdjustment = 1.0; 
    const totalDays = jd - 1948439.5 + ksaAdjustment;

    // 30 years cycle = 10631 days
    let cycles = Math.floor(totalDays / 10631);
    let rem = totalDays % 10631;
    if (rem < 0) {
      rem += 10631;
      cycles -= 1;
    }

    const isLeapYearInCycle = (yr: number): boolean => {
      return [2, 5, 7, 10, 13, 16, 18, 21, 24, 26, 29].includes(yr);
    };

    let yearInCycle = 1;
    let daysAccumulated = 0;
    while (yearInCycle <= 30) {
      const yearDays = isLeapYearInCycle(yearInCycle) ? 355 : 354;
      if (daysAccumulated + yearDays > rem) {
        break;
      }
      daysAccumulated += yearDays;
      yearInCycle++;
    }

    const hYear = cycles * 30 + yearInCycle;
    const dayInYear = rem - daysAccumulated;

    const monthDays = [30, 29, 30, 29, 30, 29, 30, 29, 30, 29, 30, isLeapYearInCycle(yearInCycle) ? 30 : 29];
    let hMonth = 0;
    let hDay = Math.floor(dayInYear) + 1;

    while (hMonth < 12 && hDay > monthDays[hMonth]) {
      hDay -= monthDays[hMonth];
      hMonth++;
    }

    const hMonth1Based = hMonth + 1;

    // Month lists
    const HIJRI_MONTHS_EN = [
      "Muharram", "Safar", "Rabi' al-Awwal", "Rabi' al-Thani",
      "Jumada al-Awwal", "Jumada al-Thani", "Rajab", "Sha'ban",
      "Ramadan", "Shawwal", "Dhu al-Qi'dah", "Dhu al-Hijjah"
    ];

    const HIJRI_MONTHS_AR = [
      "محرم", "صفر", "ربيع الأول", "ربيع الآخر",
      "جمادى الأولى", "جمادى الآخرة", "رجب", "شعبان",
      "رمضان", "شوال", "ذو القعدة", "ذو الحجة"
    ];

    const HIJRI_MONTHS_BN = [
      "মহররম", "সফর", "রবিউল আউয়াল", "রবিউস সানি",
      "জমাদিউল আউয়াল", "জমাদিউস সানি", "রজব", "শাবান",
      "রমজান", "শাওয়াল", "জিলকদ", "জিলহজ"
    ];

    // Numerals converting helper
    const toArabicDigits = (num: number): string => {
      const arabicDigits = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];
      return String(num).split('').map(char => arabicDigits[parseInt(char)] || char).join('');
    };

    const toBengaliDigits = (num: number): string => {
      const bDigits = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'];
      return String(num).split('').map(char => bDigits[parseInt(char)] || char).join('');
    };

    const finalMonthEn = HIJRI_MONTHS_EN[hMonth1Based - 1] || "Hijri Month";
    const finalMonthAr = HIJRI_MONTHS_AR[hMonth1Based - 1] || "الشهر الهجري";
    const finalMonthBn = HIJRI_MONTHS_BN[hMonth1Based - 1] || "হিজরি মাস";

    const arabic = `${toArabicDigits(hDay)} ${finalMonthAr} ${toArabicDigits(hYear)}`;
    const latin = `${hDay} ${finalMonthEn} ${hYear}`;
    const bengali = `${toBengaliDigits(hDay)} ${finalMonthBn} ${toBengaliDigits(hYear)}`;

    return {
      arabic,
      latin,
      bengali
    };
  } catch (error) {
    console.error("Hijri mathematical calculation error:", error);
    return {
      arabic: 'التاريخ الهجري',
      latin: 'Hijri Date',
      bengali: 'হিজরি তারিখ',
    };
  }
}

/**
 * Formats a Gregorian date cleanly in English + Bengali
 */
export function formatGregorianDate(dateStr: string): { english: string; bengali: string } {
  if (!dateStr) return { english: '', bengali: '' };
  const date = new Date(dateStr);
  if (isNaN(date.getTime())) return { english: '', bengali: '' };

  const options: Intl.DateTimeFormatOptions = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
  const english = new Intl.DateTimeFormat('en-US', options).format(date);
  
  const bengali = new Intl.DateTimeFormat('bn-BD', options).format(date);
  return { english, bengali };
}
